server:
  port: 8006

spring:
  application:
    name: cloud-project-service
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 123.57.180.198:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
#    url: jdbc:mysql://123.57.180.198:3306/platform_01?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.newtranx.cloud.edit.entities
  type-enums-package: com.newtranx.cloud.edit.common.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl





